# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-26 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tors',
            old_name='title',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='tors',
            name='link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
